// Audio player — loads and plays WAV files from audio_gen/output/
//
// Uses macroquad's built-in audio system (miniquad backend).
// Supports the 140 bilingual WAV files generated by generate_audio.py.

use macroquad::audio::{load_sound, play_sound, stop_sound, Sound, PlaySoundParams};
use std::collections::HashMap;
use crate::config::Language;

/// Audio player that caches loaded sounds
pub struct AudioPlayer {
    /// Cache of loaded sounds by file path
    cache: HashMap<String, Sound>,
    /// Current playing sound handle (for stopping)
    current: Option<Sound>,
    /// Master volume (0.0 - 1.0)
    volume: f32,
    /// Whether audio is enabled
    enabled: bool,
}

impl AudioPlayer {
    pub fn new() -> Self {
        Self {
            cache: HashMap::new(),
            current: None,
            volume: 0.8,
            enabled: true,
        }
    }

    /// Load a sound file (cached). Returns None if loading fails.
    pub async fn load(&mut self, path: &str) -> Option<Sound> {
        if let Some(sound) = self.cache.get(path) {
            return Some(sound.clone());
        }

        match load_sound(path).await {
            Ok(sound) => {
                self.cache.insert(path.to_string(), sound.clone());
                Some(sound)
            }
            Err(e) => {
                eprintln!("Failed to load audio {}: {}", path, e);
                None
            }
        }
    }

    /// Play a sound by path. Stops any currently playing sound first.
    pub async fn play(&mut self, path: &str) {
        if !self.enabled { return; }

        // Stop current sound
        self.stop();

        if let Some(sound) = self.load(path).await {
            play_sound(
                &sound,
                PlaySoundParams {
                    looped: false,
                    volume: self.volume,
                },
            );
            self.current = Some(sound);
        }
    }

    /// Stop the currently playing sound
    pub fn stop(&mut self) {
        if let Some(ref sound) = self.current {
            stop_sound(sound);
        }
        self.current = None;
    }

    /// Set master volume (0.0 - 1.0)
    pub fn set_volume(&mut self, volume: f32) {
        self.volume = volume.clamp(0.0, 1.0);
    }

    /// Toggle audio on/off
    pub fn toggle(&mut self) {
        self.enabled = !self.enabled;
        if !self.enabled {
            self.stop();
        }
    }

    /// Check if audio is enabled
    pub fn is_enabled(&self) -> bool {
        self.enabled
    }

    /// Get the audio path for a dialogue segment
    pub fn dialogue_audio_path(chapter_key: &str, segment_id: &str, lang: Language) -> String {
        let lang_suffix = match lang {
            Language::Chinese => "zh",
            Language::English => "en",
        };
        format!("audio_gen/output/{}/{}_{}.wav", chapter_key, segment_id, lang_suffix)
    }
}
